creation_rules:
  - path_regex: hosts/nixos-nvme/secrets.yaml$
    key_groups:
      - age:
          # YubiKey Primary
          - "age1yubikey1q2lhmqc0h6verf025hn62tkjkz25d760h54pdej7a55q4m2hszm8kwssfn0"
          # YubiKey Backup
          - "age1yubikey1qg379rzgajvstx6vhk2fsvc0eu9zyjjk7q24pd3pf5dq22xvlqew23e08l2"
