# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Please make changes to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "ums_realtek" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/1f46beca-dc9a-481b-86fe-275a697e3dc2";
    preLVM = true;
  };

  boot.initrd.services.lvm.enable = true;

  boot.kernelModules = [ "kvm-intel" ];
  # Removed boot.kernelPackages here; it is now in configuration.nix
  boot.extraModulePackages = [ ];

  # Removed manual boot.kernelParams; they are now in configuration.nix

  fileSystems."/" =
    { device = "/dev/mapper/vg0-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D223-DA20";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var" =
    { device = "/dev/mapper/vg0-var";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/vg0-home";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/vg0-nix";
      fsType = "btrfs";
    };

  fileSystems."/images" =
    { device = "/dev/mapper/vg0-images";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/vg0-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Removed updateMicrocode here to avoid conflicts; it is now in configuration.nix
}