#!/usr/bin/env python3
"""Generate nix-config/docs/IMPORTS.md — a per-host import map.

For every host directory under nix-config/hosts/, parses the top-level
`imports = [ … ]` block and categorizes each entry (module / preset / hardware
/ user / local / other). Also emits a reverse index so a "who imports X?"
question becomes a single grep.

Complements OPTIONS.md: that index covers *opted-in* options, while this one
covers the *raw module imports* — including modules with no `my.*` options
(common.nix, hosts.nix, scripts.nix, …) and inputs from sibling flakes.

Regenerated by `just maintenance::sync-agent`. Static analysis only.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _nix_options import (  # noqa: E402
    REPO,
    extract_imports_in_file,
    relpath,
)

HOSTS_DIR = REPO / "nix-config/hosts"
OUTPUT = REPO / "nix-config/docs/IMPORTS.md"

# Order in which to render kind buckets per host. Stable for grep.
KIND_ORDER = ["module", "preset", "hardware", "user", "other", "local"]
KIND_LABEL = {
    "module": "Modules",
    "preset": "Presets",
    "hardware": "Hardware",
    "user": "Users",
    "local": "Local",
    "other": "Other inputs",
}


def collect_host_imports() -> dict[str, list]:
    """For each host directory, return its top-level imports list."""
    out: dict[str, list] = {}
    if not HOSTS_DIR.exists():
        return out
    for host_dir in sorted(p for p in HOSTS_DIR.iterdir() if p.is_dir()):
        entry_file = host_dir / "default.nix"
        if not entry_file.exists():
            # Some hosts use a different entry filename (e.g. nix-on-droid)
            candidates = [p for p in host_dir.glob("*.nix") if p.name != "secrets.nix"]
            if not candidates:
                continue
            entry_file = candidates[0]
        entries = extract_imports_in_file(entry_file)
        out[host_dir.name] = entries
    return out


def main() -> int:
    host_imports = collect_host_imports()
    if not host_imports:
        print(
            "No host imports found — refusing to overwrite IMPORTS.md", file=sys.stderr
        )
        return 1

    # Reverse index: label → set of hosts
    reverse: dict[str, set[str]] = defaultdict(set)
    for host, entries in host_imports.items():
        for e in entries:
            reverse[e.label].add(host)

    lines: list[str] = []
    lines.append("# Host Import Graph")
    lines.append("")
    lines.append(
        "> **Auto-generated** by `nix-config/scripts/generate-imports-index.py`. Do not edit by hand."
    )
    lines.append(">")
    lines.append("> Regenerate with `just maintenance::sync-agent`.")
    lines.append("")
    lines.append(
        "Top-level imports per host, plus a reverse index. Use this alongside "
        "`OPTIONS.md` — that one shows opted-in `my.*` options, this one shows "
        "raw module imports (including modules with no `my.*` options)."
    )
    lines.append("")
    lines.append(f"**Hosts indexed:** {len(host_imports)}  ")
    lines.append(f"**Distinct imports:** {len(reverse)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-host section
    lines.append("## Per host")
    lines.append("")
    for host in sorted(host_imports):
        entries = host_imports[host]
        lines.append(f"### `{host}`")
        lines.append("")
        if not entries:
            lines.append(
                "_(no imports detected — host may use a non-standard entry file)_"
            )
            lines.append("")
            continue
        by_kind: dict[str, list[str]] = defaultdict(list)
        for e in entries:
            by_kind[e.kind].append(e.label)
        for k in KIND_ORDER:
            if k not in by_kind:
                continue
            items = sorted(set(by_kind[k]))
            lines.append(f"- **{KIND_LABEL[k]}:** {', '.join(f'`{x}`' for x in items)}")
        lines.append("")

    # Reverse index
    lines.append("## Reverse index — import → hosts")
    lines.append("")
    for label in sorted(reverse):
        hosts = sorted(reverse[label])
        lines.append(f"- `{label}` ← {', '.join(hosts)}")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"✅ Wrote {relpath(OUTPUT)} ({len(host_imports)} hosts, {len(reverse)} distinct imports)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
