#!/usr/bin/env bash
set -e

TODAY=$(date +%Y-%m-%d)
REPORT_FILE=".agent/audit/${TODAY}_scan.md"

# Helper for printing headers
function h2() {
    echo "" >> "$REPORT_FILE"
    echo "## $1" >> "$REPORT_FILE"
    echo "Scanning $1..."
}

echo "# Security Audit Report - ${TODAY}" > "$REPORT_FILE"
echo "**Generated by:** Antigravity Secure Scan Protocol" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ==============================================================================
# 1. KNOWN VULNERABILITIES (CVEs)
# ==============================================================================
h2 "1. Vulnerability Scan (vulnix)"
echo "Checking system closure for known CVEs..."
echo "\`\`\`" >> "$REPORT_FILE"

# Run vulnix on the entire system closure
# We use --json for machine parsing if needed, but text is verifyable by human
if vulnix --whitelists .agent/audit/whitelist.toml . >> "$REPORT_FILE" 2>&1; then
  echo "✅ No known vulnerabilities found."
else
  # Vulnix returns non-zero if vulnerabilities are found
  echo "⚠️  Vulnerabilities detected! Check report."
fi
echo "\`\`\`" >> "$REPORT_FILE"

# ==============================================================================
# 2. STATIC ANALYSIS (Linting)
# ==============================================================================
h2 "2. Static Code Analysis (statix)"
echo "Linting Nix code for security anti-patterns..."
echo "\`\`\`" >> "$REPORT_FILE"
if statix check . >> "$REPORT_FILE" 2>&1; then
    echo "✅ Code looks clean."
    echo "No issues found." >> "$REPORT_FILE"
else
    echo "⚠️  Static analysis found issues."
fi
echo "\`\`\`" >> "$REPORT_FILE"

# ==============================================================================
# 3. DEAD CODE DETECTION
# ==============================================================================
h2 "3. Dead Code Detection (deadnix)"
echo "Scanning for unused code..."
echo "\`\`\`" >> "$REPORT_FILE"
if deadnix . >> "$REPORT_FILE" 2>&1; then
    echo "✅ No dead code found."
    echo "No dead code found." >> "$REPORT_FILE"
else
    echo "⚠️  Dead code detected."
fi
echo "\`\`\`" >> "$REPORT_FILE"

# ==============================================================================
# 4. CONFIGURATION COMPLIANCE
# ==============================================================================
h2 "4. Configuration Compliance Checks"
echo "Verifying critical security settings..."

# Function to check a Nix option value
check_option() {
    local host=$1
    local option=$2
    local expected=$3
    
    echo -n "- Checking $option on $host... " >> "$REPORT_FILE"
    
    # Eval the option from the flake
    ACTUAL=$(nix eval --raw ".#nixosConfigurations.$host.config.$option" 2>/dev/null || echo "ERROR")
    
    if [[ "$ACTUAL" == "$expected" ]]; then
        echo "✅ PASS" >> "$REPORT_FILE"
    else
        echo "❌ FAIL (Expected: $expected, Got: $ACTUAL)" >> "$REPORT_FILE"
        echo "⚠️  Compliance Fail: $option"
    fi
}

echo "### Workstation Compliance" >> "$REPORT_FILE"
check_option "workstation" "services.openssh.settings.PermitRootLogin" "prohibit-password"
check_option "workstation" "services.openssh.settings.PasswordAuthentication" "no"
check_option "workstation" "networking.firewall.enable" "true"
check_option "workstation" "nix.settings.trusted-users.0" "root"

# ==============================================================================
# 5. SECRET SCAN
# ==============================================================================
h2 "5. Data Leak Scan"
echo "Scanning for personal data (Emails, Keys, Tokens)..."

# Regex for common leaks
# 1. Private Keys (BEGIN RSA...)
# 2. AWS/API Tokens
# 3. Emails (aggressive)
LEAK_REGEX="(BEGIN .* PRIVATE KEY|AWS_ACCESS_KEY_ID|AKIA[0-9A-Z]{16}|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})"

# We use grep with line numbers, then filter out known safe patterns
if grep -rE "$LEAK_REGEX" . \
    --exclude-dir=.git \
    --exclude-dir=.agent \
    --exclude-dir=result \
    --exclude="flake.lock" \
    | grep -vFf <(jq -r '.[]' .agent/audit/grep_ignore.json) >> "$REPORT_FILE"; then
    
    echo "❌ POTENTIAL LEAK FOUND" >> "$REPORT_FILE"
    echo "🚨 ALERT: Potential sensitive data found! Check report."
else
    echo "✅ No sensitive patterns found." >> "$REPORT_FILE"
    echo "✅ No leaks detected."
fi

echo ""
echo "📄 Detailed Report generated at: ${REPORT_FILE}"
cat "$REPORT_FILE" | gum format # Use glow/gum to display if available
