add_newline = true
scan_timeout = 10

# Custom format to include devshell name
format = """
$directory\
$git_branch\
$git_status\
$env_var\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 0
truncate_to_repo = false

[git_status]
disabled = false
ignore_submodules = true

[nix_shell]
disabled = true

[env_var.DEV_SHELL_NAME]
variable = "DEV_SHELL_NAME"
format = "via [$symbol$value]($style) "
style = "bold blue"
symbol = " " # Default symbol, will be overridden if we use the STARSHIP_SHELL_SYMBOL
