{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.services.container-updater;
  hostSystem = pkgs.stdenv.hostPlatform.system;
  # Guard: only real nspawn containers can be staged. Hosts auto-derive their
  # list from `my.containers` enables, which also covers OCI/podman services
  # (comfyui, vllm, langflow) that have no nspawn closure and thus no manifest
  # entry — intersecting with `config.containers` filters those out.
  registered = lib.filter (c: builtins.hasAttr c config.containers) cfg.containers;
in
{
  options.my.services.container-updater = {
    enable = lib.mkEnableOption "Automated container closures updater via Nix Profiles";
    manifestUrl = lib.mkOption {
      type = lib.types.str;
      default = "https://github.com/kleinbem/nix-config/releases/download/container-manifest/manifest.json";
      description = ''
        URL of the CI-published container manifest: a JSON map of
        system → container name → store path, generated by the
        promote-production workflow for the exact SHA the `production`
        tag points at. Consuming the manifest instead of evaluating the
        flake keeps the nightly update eval-free on the device — an
        RPi-class host only fetches a JSON file and substitutes a store
        path from the binary cache.
      '';
    };
    containers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "List of standalone containers to auto-update.";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd = {
      # ----------------------------------------------------------------
      # Stage: resolve the container's closure from the CI manifest,
      # substitute it from the binary cache, register as profile, swap
      # symlink. NO nix evaluation happens on the device. The running
      # container is NOT touched — it keeps serving the old closure
      # until activated. When the staged path differs from the previous
      # profile target, a change flag is dropped in /run so the bulk
      # orchestrator only restarts containers that actually changed.
      # ----------------------------------------------------------------
      services = {
        "update-container-stage@" = {
          description = "Stage update for NixOS Container %i (no restart)";
          after = [ "network-online.target" ];
          wants = [ "network-online.target" ];

          path = with pkgs; [
            nix
            systemd
            curl
            jq
          ];

          scriptArgs = "%i";
          script = ''
            CONTAINER=$1
            echo "Staging update for container: $CONTAINER (system: ${hostSystem})"

            echo "Fetching manifest ${cfg.manifestUrl}..."
            MANIFEST=$(curl -fsSL --retry 3 --max-time 60 "${cfg.manifestUrl}")

            REV=$(echo "$MANIFEST" | jq -r '.rev // "unknown"')
            STORE_PATH=$(echo "$MANIFEST" \
              | jq -r --arg sys "${hostSystem}" --arg c "$CONTAINER" \
                  '.systems[$sys][$c] // empty')

            if [ -z "$STORE_PATH" ]; then
              echo "Container $CONTAINER has no entry for ${hostSystem} in manifest (rev $REV)."
              echo "Either CI has not built it for this arch yet, or the name is wrong. Aborting."
              exit 1
            fi

            echo "Manifest (rev $REV): $CONTAINER -> $STORE_PATH"
            echo "Substituting from binary cache..."
            nix-store --realise "$STORE_PATH"

            PROFILE="/nix/var/nix/profiles/containers/$CONTAINER"
            OLD_PATH=$(readlink -f "$PROFILE" 2>/dev/null || echo "none")

            echo "Registering $CONTAINER as a Nix profile (GC safe)..."
            nix-env --profile "$PROFILE" --set "$STORE_PATH"

            # Defensive: /var/lib/machines/<name>/ is normally created by the NixOS
            # containers module when my.containers.<name>.enable = true on this host.
            # Create it ourselves if missing so a one-off update for a never-deployed
            # container doesn't fail at the symlink swap.
            mkdir -p "/var/lib/machines/$CONTAINER"

            echo "Updating symlink /var/lib/machines/$CONTAINER/current..."
            ln -sfn "$PROFILE" "/var/lib/machines/$CONTAINER/current"

            if [ "$OLD_PATH" != "$STORE_PATH" ]; then
              touch "/run/container-updater/changed-$CONTAINER"
              echo "Closure changed ($OLD_PATH -> $STORE_PATH); activation needed."
            else
              echo "Closure unchanged; no restart needed."
            fi

            echo "Stage complete for $CONTAINER. Activate with:"
            echo "  systemctl start update-container-activate@$CONTAINER.service"
          '';

          serviceConfig = {
            Type = "oneshot";
            TimeoutStartSec = "15m";
          };
        };

        # ----------------------------------------------------------------
        # Activate: restart the container so it picks up the staged closure.
        # ~5-30s downtime per container. Must be run AFTER stage.
        # ----------------------------------------------------------------
        "update-container-activate@" = {
          description = "Activate staged update for NixOS Container %i (restart)";

          path = with pkgs; [ systemd ];

          scriptArgs = "%i";
          script = ''
            CONTAINER=$1
            if machinectl status "$CONTAINER" >/dev/null 2>&1; then
              echo "Restarting container $CONTAINER to apply staged update..."
              machinectl restart "$CONTAINER"
            else
              echo "Container $CONTAINER is not currently running. Starting it..."
              systemctl start "container@$CONTAINER"
            fi
            rm -f "/run/container-updater/changed-$CONTAINER"
            echo "Activation complete for $CONTAINER."
          '';

          serviceConfig = {
            Type = "oneshot";
            TimeoutStartSec = "5m";
          };
        };

        # ----------------------------------------------------------------
        # Combined stage + activate (backward-compatible entry point).
        # Equivalent to the original update-container@ behaviour: fetch,
        # swap, restart, all in one shot. Restart is unconditional here —
        # this is the manual "make it so" button.
        # ----------------------------------------------------------------
        "update-container@" = {
          description = "Update NixOS Container %i (stage + activate)";

          path = with pkgs; [ systemd ];

          scriptArgs = "%i";
          script = ''
            CONTAINER=$1
            systemctl start --wait "update-container-stage@$CONTAINER.service"
            systemctl start --wait "update-container-activate@$CONTAINER.service"
          '';

          serviceConfig = {
            Type = "oneshot";
            TimeoutStartSec = "20m";
          };
        };

        # ----------------------------------------------------------------
        # Bulk orchestrator: three-phase update of every registered
        # container, designed to avoid the attic-eats-itself bootstrap
        # window. Stage everything in parallel (no restarts → attic keeps
        # serving). Then activate non-attic in parallel. Then attic last.
        # Only containers whose staged closure actually CHANGED are
        # restarted — an unchanged container (e.g. home-assistant between
        # releases) is left untouched instead of blipping nightly.
        # ----------------------------------------------------------------
        "update-containers" = lib.mkIf (registered != [ ]) {
          description = "Smart bulk update of standalone NixOS containers (stage all → activate changed non-attic → activate attic last)";

          path = with pkgs; [ systemd ];

          serviceConfig = {
            Type = "oneshot";
            TimeoutStartSec = "1h";
          };

          script = ''
            set -e
            CONTAINERS="${lib.concatStringsSep " " registered}"

            echo "=== Phase 1: staging updates for all containers in parallel ==="
            for c in $CONTAINERS; do
              echo "  staging $c..."
              systemctl start --wait "update-container-stage@$c.service" &
            done
            wait
            echo "All stages complete."

            needs_activation() {
              # Restart if the closure changed OR the container isn't running
              # (e.g. first stage after enabling: ConditionPathExists held it back).
              [ -e "/run/container-updater/changed-$1" ] && return 0
              machinectl status "$1" >/dev/null 2>&1 && return 1
              return 0
            }

            echo "=== Phase 2: activating changed non-attic containers in parallel ==="
            for c in $CONTAINERS; do
              if [ "$c" != "attic" ] && needs_activation "$c"; then
                echo "  activating $c..."
                systemctl start --wait "update-container-activate@$c.service" &
              fi
            done
            wait
            echo "Non-attic activations complete."

            if echo " $CONTAINERS " | grep -q " attic " && needs_activation attic; then
              echo "=== Phase 3: activating attic last ==="
              systemctl start --wait "update-container-activate@attic.service"
            fi

            echo "Bulk update complete."
          '';
        };

        # ----------------------------------------------------------------
        # Bootstrap: standalone container@ units carry
        # ConditionPathExists=/var/lib/machines/<name>/current, so on a
        # host that just switched a container from embedded to standalone
        # (or on a fresh install) the container stays DOWN until first
        # staged. Don't wait for the 03:00 timer — stage + start any
        # registered container whose symlink is missing, right at boot.
        # ----------------------------------------------------------------
        "container-updater-bootstrap" = lib.mkIf (registered != [ ]) {
          description = "Bootstrap standalone containers that have never been staged";
          after = [ "network-online.target" ];
          wants = [ "network-online.target" ];
          wantedBy = [ "multi-user.target" ];

          path = with pkgs; [ systemd ];

          serviceConfig = {
            Type = "oneshot";
            TimeoutStartSec = "30m";
          };

          script = ''
            CONTAINERS="${lib.concatStringsSep " " registered}"
            for c in $CONTAINERS; do
              if [ ! -e "/var/lib/machines/$c/current" ]; then
                echo "Container $c has no staged closure — bootstrapping..."
                systemctl start --wait "update-container@$c.service" || \
                  echo "Bootstrap of $c failed; it will retry on the nightly timer."
              fi
            done
          '';
        };
      };

      timers."update-containers" = lib.mkIf (registered != [ ]) {
        description = "Nightly update of standalone NixOS containers";
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = "*-*-* 03:00:00";
          Persistent = true;
          RandomizedDelaySec = "30m";
        };
      };

      # Ensure the profiles + change-flag directories exist
      tmpfiles.rules = [
        "d /nix/var/nix/profiles/containers 0755 root root - -"
        "d /run/container-updater 0755 root root - -"
      ];
    };
  };
}
