{
  pkgs,
  inputs,
  lib,
  config,
  ...
}:

{
  # ==========================================
  # NIX SETTINGS & CORE
  # ==========================================
  time.timeZone = "Europe/Dublin";
  i18n.defaultLocale = "en_IE.UTF-8";
  console.keyMap = "us";

  nixpkgs.config.allowUnfree = true;
  nix = {
    registry.nixpkgs.flake = inputs.nixpkgs;
    settings = {
      experimental-features = [
        "nix-command"
        "flakes"
      ];
      auto-optimise-store = true;
      substituters = [
        "https://cache.nixos.org"
        "https://nix-community.cachix.org"
        "https://cosmic.cachix.org"
      ];
      trusted-public-keys = [
        "cache.nixos.org-1:Ik/ZBziETSRre3nCpv7l4WwhDD5OhoOx9LG/mIJV6Hg="
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
        "cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE="
      ];
      download-buffer-size = 1073741824;

      # Binary Cache Optimization
      builders-use-substitutes = true;
      connect-timeout = 5; # Fallback quickly if cache is down, BUT:
      # we actually want to wait longer if the issue is just slow connection
      # to avoid building from source.

      log-lines = 25;
      min-free = 1073741824; # 1GB
      max-jobs = 4;
      cores = 2;
      trusted-users = [
        "@wheel"
      ];
    };
    daemonCPUSchedPolicy = "idle";
    daemonIOSchedClass = "idle";
    # We use !include to read the file generated by sops-nix
    # extraOptions = ''
    #   !include ${config.sops.secrets.github_read_all_token.path}
    # '';
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  # Prevent /var/log/journal from growing indefinitely
  services.journald.extraConfig = "SystemMaxUse=1G";

  # Web-based System Administration
  services.cockpit = {
    enable = true;
    port = 9091;
    openFirewall = true;
    settings = {
      WebService = {
        Origins = lib.mkForce "https://10.85.46.107:9090";
        ProtocolHeader = "X-Forwarded-Proto";
      };
    };
  };

  # Ensure /etc/cockpit is a writable directory (not a symlink to read-only store)
  # and link the config file inside it, avoiding "Read-only file system" errors.
  systemd.tmpfiles.rules = [
    "d /etc/cockpit 0755 root root -"
    "L+ /etc/cockpit/cockpit.conf - - - - /etc/static/cockpit/cockpit.conf"
    "d /etc/cockpit/ws-certs.d 0755 nobody nobody -"
  ];

  # Alias kexec-load to kdump to satisfy Cockpit's check
  systemd.services.kdump = {
    description = "Kdump Service Alias (kexec-load)";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.coreutils}/bin/true";
      RemainAfterExit = true;
    };
    unitConfig.Documentation = "man:kexec-load(8)";
  };

  # Generic Boot Preferences
  boot.loader.timeout = 2; # Fast boot

  # Massive Swap (Essential for AI workloads)
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  # ==========================================
  # CORE UTILITIES
  # ==========================================
  programs = {
    # Allow non-root users to mount FUSE
    fuse.userAllowOther = true;

    # Run unpatched binaries
    nix-ld.enable = true;
    nix-ld.libraries = with pkgs; [
      zlib
      zstd
      stdenv.cc.cc
      curl
      openssl
      attr
      libssh
      bzip2
      libxml2
      acl
      libsodium
      util-linux
      xz
      systemd
      glib
      gtk3
      libuuid
      icu
      libuv
      stdenv.cc.cc.lib
    ];

    # Command Discovery (command-not-found alternative)
    nix-index.enable = true;
  };

  environment.systemPackages = with pkgs; [
    # Core Tools
    git
    curl
    wget
    btop
    ouch
    file
    pciutils

    # Modern CLI Tools
    gh
    just
    jq
    ripgrep
    fd
    eza
    nh
    nix-output-monitor
    nvd

    # Nix Tooling
    nixfmt
    deadnix
    statix

    # Cockpit Tools
    cockpit-machines
    cockpit-podman
    cockpit-files
    kexec-tools # Kernel Crash Dumps
    sosreport # System Analysis
    android-tools # ADB & Fastboot
  ];

  # Enable Kernel Crash Dumps (satisfies Cockpit Kdump check)
  boot.crashDump.enable = true;

  environment.sessionVariables = {
    FLAKE = "${config.my.developDir}/nix-config";
    NH_FLAKE = "${config.my.developDir}/nix-config"; # nh 4.2+ support
  };

  # ==========================================
  # AUTOMATED SECURITY UPDATES
  # ==========================================
  system.autoUpgrade = {
    enable = true;
    flake = "${config.my.developDir}/nix/nix-config";
    flags = [
      "--update-input"
      "nixpkgs"
    ];
    dates = "04:00";
    allowReboot = false; # Stage only — user controls reboots
    randomizedDelaySec = "30min";
  };
}
