{
  inputs,
  pkgs,
  lib,
  my,
  ...
}:
let
  keys = import ../../modules/nixos/keys.nix;
  personasLib = import ../../lib/personas.nix { inherit lib; };
in
{
  imports = [
    ../../modules/home-manager/default.nix
    ../../modules/home-manager/gnome.nix
    inputs.nix-devshells.homeManagerModules.desktopLaunchers
  ];

  modules = {
    devshell-launchers.enable = true;
    service-launchers.enable = true;
    mcp.enable = true;
    opencode.enable = true;
    gnome.enable = true;
    syncthing.enable = false; # Migrated to system container fleet
    workspace-guardian.enable = true;
  };

  # User Details
  home = {
    inherit (my) username;
    homeDirectory = my.home;
    stateVersion = "25.11";
    sessionVariables = {
      DEFAULT_BROWSER = "${pkgs.firefox-beta}/bin/firefox -P standard";
      BROWSER = "${pkgs.firefox-beta}/bin/firefox -P standard";
      # mkForce: the neovim wrapper module also sets EDITOR (nvim); nano wins
      # so sops/git/etc. open a friendlier editor.
      EDITOR = lib.mkForce "nano";
    };

    # Personal System Control Center — `os <ns>::<recipe>`. The `os`
    # shell alias lives in nix-presets/terminal.nix (generic); these
    # source files are martin-specific (Obsidian paths, etc.) and so
    # belong in martin's user dir rather than a shared preset.
    file = {
      ".justfile" = {
        source = ./files/justfile;
        force = true;
      };
      ".just" = {
        source = ./files/.just;
        recursive = true;
      };

      # Declarative ~/.ssh/allowed_signers. Git resolves signatures
      # against this file (see nix-presets/git.nix: gpg.ssh.allowedSignersFile).
      #
      # Principal `*` matches any committer email — so Martin's hardware
      # keys verify regardless of which identity (gmail / kleinbem.dev)
      # the commit was made under.
      #
      # Persona keys are rendered from keys.ssh.personas. Until those
      # entries are populated (Phase 1 — Stalwart provisioning), the
      # renderer emits nothing for them.
      ".ssh/allowed_signers" = {
        force = true;
        text = ''
          # Auto-generated by home-manager.
          # Source: nix-config/modules/nixos/keys.nix (ssh.fido2*)
          #         nix-config/personas.nix + nix-config/modules/nixos/keys.nix:ssh.personas
          # DO NOT EDIT — rebuild home-manager to regenerate.

          * ${keys.ssh.fido2}
          * ${keys.ssh.fido2-backup}
          * ${keys.ssh.fido2-notouch}

          ${personasLib.allowedSigners keys.ssh.personas}'';
      };

      # Obsidian Excalidraw Plugin
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/main.js".source = pkgs.fetchurl {
        url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.25.0/main.js";
        sha256 = "18zlwx6fqpijfz5ib3v6j2dysjm4ksz1srzka53lp1ar4ffkm61j";
      };
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/manifest.json".source =
        pkgs.fetchurl
          {
            url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.25.0/manifest.json";
            sha256 = "1ls2371p0cv906qjzkyn9054lgwhhjgi0vbrqmqgl01iv2yzf2mh";
          };
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/styles.css".source = pkgs.fetchurl {
        url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.25.0/styles.css";
        sha256 = "1xc4qn0ryaxds707j3ifd78n09j1jq50c2ybp04kxfamfj2kzfv8";
      };
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/http" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/https" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/about" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/unknown" = [ "firefox-standard.desktop" ];
    };
  };

  programs = {
    firefox-browser.enable = true;
    home-manager.enable = true;

    # Inject hardware-protected signing keys from centralized proxy
    git.settings.user.signingKey = "${my.home}/.ssh/id_ed25519_sk_rk_GitHubNoTouchV2.pub";
    # jj's ssh backend wants a public-key file path; the `key::<blob>` form
    # is git-specific and silently breaks signing in jj.
    jujutsu.settings.signing.key = "${my.home}/.ssh/id_ed25519_sk_rk_GitHubNoTouchV2.pub";

    # SSH multiplexing for github.com — first touch-required FIDO op opens a
    # master connection; subsequent SSH ops within ControlPersist reuse it
    # without a fresh touch. Dramatically reduces YubiKey touches during
    # `just apply` (was ~6 touches per apply, now typically 1-2).
    #
    # If stale sockets ever cause "Session open refused by peer" hangs, run:
    #   ssh -O exit git@github.com 2>/dev/null; rm -f ~/.ssh/cm-*
    ssh = {
      enable = true;
      settings = {
        "github.com" = {
          Hostname = "github.com";
          User = "git";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "10m";
        };

        # hass-pi (Raspberry Pi 5, Home Assistant node). root is locked on the
        # booted system, so connect as martin + sudo. The login key is a FIDO2
        # hardware key (id_ed25519_sk); ssh-agent can't do PIN entry for it
        # ("agent refused operation"), so bypass the agent (IdentityAgent none)
        # and hand ssh the key file directly — it then prompts for PIN + touch.
        #
        # ControlMaster multiplexing (same trick as github.com above): the FIRST
        # connection costs one PIN+touch and opens a master socket; every later
        # `ssh hass-pi` / `just hass-pi::*` within ControlPersist reuses it with
        # NO further touch. So it's ~1 touch per session window, not per command.
        # (For YubiKey-free access from machines without a key, use NetBird SSH:
        #  `netbird ssh hass-pi` once hass-pi is enrolled — auth is the peer
        #  identity, no hardware key involved.)
        "hass-pi" = {
          Hostname = "10.0.0.21";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage: root on port 2222 (clevis/tang usually unlocks
        # automatically; this is the manual fallback).
        "hass-pi-initrd" = {
          Hostname = "10.0.0.21";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
        "core-pi" = {
          Hostname = "10.0.0.22";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage for core-pi
        "core-pi-initrd" = {
          Hostname = "10.0.0.22";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
        # orin-nano (Jetson Orin Nano, AI edge node). Same FIDO2-SK-via-agent
        # failure as the Pis ("agent refused operation") — bypass the agent so the
        # key signs. Match the IP too, so `ssh …10.0.0.15` gets it, not just the alias.
        "orin-nano 10.0.0.15" = {
          Hostname = "10.0.0.15";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage for orin-nano (manual fallback; Tang auto-unlocks)
        "orin-nano-initrd" = {
          Hostname = "10.0.0.15";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
      };
    };
  };

  # Desktop Launchers
  xdg.desktopEntries = {
    "launch-nested-dhirujaan" = {
      name = "Nested Session (Dhirujaan)";
      genericName = "Lightweight Wayland Session";
      exec = "sudo /home/martin/Develop/github.com/kleinbem/nix/nix-config/scripts/launch-nested.sh";
      icon = "system-users";
      terminal = true;
      categories = [ "System" ];
    };
  };

  # Silencing evaluation warnings from newer Home Manager
  # (Using null adopts the new default behavior)
  gtk.gtk4.theme = null;
}
