{
  inputs,
  pkgs,
  lib,
  my,
  myInventory,
  ...
}:
let
  keys = import ../../modules/nixos/keys.nix;
  personasLib = import ../../lib/personas.nix { inherit lib; };
in
{
  imports = [
    ../../modules/home-manager/default.nix
    ../../modules/home-manager/gnome.nix
    inputs.nix-devshells.homeManagerModules.desktopLaunchers
  ];

  modules = {
    devshell-launchers.enable = true;
    service-launchers.enable = true;
    mcp.enable = true;
    opencode.enable = true;
    gnome.enable = true;
    syncthing.enable = false; # Migrated to system container fleet
    workspace-guardian.enable = true;
  };

  # bitwarden-desktop's clipboard.write is broken on GNOME/Mutter (see
  # gnome.nix's xdg.desktopEntries.bitwarden comment) — Mutter doesn't
  # implement the zwlr_data_control_manager_v1 protocol Bitwarden's Rust
  # clipboard lib insists on. A normal user-gesture browser copy uses the
  # plain wl_data_device protocol instead, which Mutter fully supports, so
  # the web vault as a PWA sidesteps the bug entirely (same reasoning as the
  # already-working Firefox extension, just via Chromium for a standalone
  # app window instead of a browser tab).
  my.pwa = {
    enable = true;
    apps.bitwarden = {
      name = "Bitwarden";
      url = "https://vault.bitwarden.com";
      svg = ''
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
          <rect width="512" height="512" rx="96" fill="#175DDC"/>
          <path fill="#ffffff" d="M256 96 L384 144 V256 C384 336 328 400 256 424 C184 400 128 336 128 256 V144 Z"/>
          <path fill="#175DDC" fill-opacity="0.18" d="M256 140 L344 172 V256 C344 316 306 360 256 380 Z"/>
        </svg>
      '';
      categories = [
        "Utility"
        "Network"
      ];
    };
  };

  # User Details
  home = {
    inherit (my) username;
    homeDirectory = my.home;
    stateVersion = "25.11";
    sessionVariables = {
      DEFAULT_BROWSER = "${pkgs.firefox-beta}/bin/firefox -P standard";
      BROWSER = "${pkgs.firefox-beta}/bin/firefox -P standard";
      # mkForce: the neovim wrapper module also sets EDITOR (nvim); nano wins
      # so sops/git/etc. open a friendlier editor.
      EDITOR = lib.mkForce "nano";
      # buzz-desktop (nixos-nvme systemPackages) needs this to connect to
      # the self-hosted relay. First attempt used NixOS-level
      # environment.variables (hosts/nixos-nvme/default.nix) — wrong
      # mechanism: that only applies via /etc/set-environment at login
      # time, confirmed live 2026-08-10 to stay empty in a fresh terminal
      # even after a full switch. home.sessionVariables is what BROWSER/
      # DEFAULT_BROWSER above already use and is proven to reach new
      # terminals without a relogin — same fix, right place this time.
      # Harmless on hosts without buzz-desktop installed.
      BUZZ_RELAY_URL = "ws://${myInventory.network.nodes.buzz.ip}:3000";
    };

    # Personal System Control Center — `os <ns>::<recipe>`. The `os`
    # shell alias lives in nix-presets/terminal.nix (generic); these
    # source files are martin-specific (Obsidian paths, etc.) and so
    # belong in martin's user dir rather than a shared preset.
    file = {
      ".justfile" = {
        source = ./files/justfile;
        force = true;
      };
      ".just" = {
        source = ./files/.just;
        recursive = true;
      };

      # Declarative ~/.ssh/allowed_signers. Git resolves signatures
      # against this file (see nix-presets/git.nix: gpg.ssh.allowedSignersFile).
      #
      # Principal `*` matches any committer email — so Martin's hardware
      # keys verify regardless of which identity (gmail / kleinbem.dev)
      # the commit was made under.
      #
      # Persona keys are rendered from keys.ssh.personas. Until those
      # entries are populated (Phase 1 — Stalwart provisioning), the
      # renderer emits nothing for them.
      ".ssh/allowed_signers" = {
        force = true;
        text = ''
          # Auto-generated by home-manager.
          # Source: nix-config/modules/nixos/keys.nix (ssh.fido2*)
          #         nix-config/personas.nix + nix-config/modules/nixos/keys.nix:ssh.personas
          # DO NOT EDIT — rebuild home-manager to regenerate.

          * ${keys.ssh.fido2}
          * ${keys.ssh.fido2-backup}
          * ${keys.ssh.fido2-notouch}

          ${personasLib.allowedSigners keys.ssh.personas}'';
      };

      # Obsidian Excalidraw Plugin
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/main.js".source = pkgs.fetchurl {
        url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.26.4/main.js";
        sha256 = "0nngsir7z0fx7g74wkfav11cdz8az11jxj0iikzgx753rz43yvxj";
      };
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/manifest.json".source =
        pkgs.fetchurl
          {
            url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.26.4/manifest.json";
            sha256 = "00xp43032cilnlxgzwb54kshdn68rlv74bd6f5k118igxbd1gf7n";
          };
      "Documents/Notes/.obsidian/plugins/obsidian-excalidraw-plugin/styles.css".source = pkgs.fetchurl {
        url = "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/download/2.26.4/styles.css";
        sha256 = "0d97qjq41a08vngwfcq3qi8vq4vrh394867zyd7cmclka465cnv1";
      };
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/http" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/https" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/about" = [ "firefox-standard.desktop" ];
      "x-scheme-handler/unknown" = [ "firefox-standard.desktop" ];
    };
  };

  programs = {
    firefox-browser.enable = true;
    home-manager.enable = true;

    # Inject hardware-protected signing keys from centralized proxy
    git.settings.user.signingKey = "${my.home}/.ssh/id_ed25519_sk_rk_GitHubNoTouchV2.pub";
    # jj's ssh backend wants a public-key file path; the `key::<blob>` form
    # is git-specific and silently breaks signing in jj.
    jujutsu.settings.signing.key = "${my.home}/.ssh/id_ed25519_sk_rk_GitHubNoTouchV2.pub";

    # SSH multiplexing for github.com — first touch-required FIDO op opens a
    # master connection; subsequent SSH ops within ControlPersist reuse it
    # without a fresh touch. Dramatically reduces YubiKey touches during
    # `just apply` (was ~6 touches per apply, now typically 1-2).
    #
    # If stale sockets ever cause "Session open refused by peer" hangs, run:
    #   ssh -O exit git@github.com 2>/dev/null; rm -f ~/.ssh/cm-*
    ssh = {
      enable = true;
      settings = {
        "github.com" = {
          Hostname = "github.com";
          User = "git";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "10m";
        };

        # hass-pi (Raspberry Pi 5, Home Assistant node). root is locked on the
        # booted system, so connect as martin + sudo. The login key is a FIDO2
        # hardware key (id_ed25519_sk); ssh-agent can't do PIN entry for it
        # ("agent refused operation"), so bypass the agent (IdentityAgent none)
        # and hand ssh the key file directly — it then prompts for PIN + touch.
        #
        # ControlMaster multiplexing (same trick as github.com above): the FIRST
        # connection costs one PIN+touch and opens a master socket; every later
        # `ssh hass-pi` / `just hass-pi::*` within ControlPersist reuses it with
        # NO further touch. So it's ~1 touch per session window, not per command.
        # (For YubiKey-free access from machines without a key, use NetBird SSH:
        #  `netbird ssh hass-pi` once hass-pi is enrolled — auth is the peer
        #  identity, no hardware key involved.)
        "hass-pi" = {
          Hostname = "10.0.0.21";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage: root on port 2222 (clevis/tang usually unlocks
        # automatically; this is the manual fallback).
        "hass-pi-initrd" = {
          Hostname = "10.0.0.21";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
        "core-pi" = {
          Hostname = "10.0.0.22";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage for core-pi
        "core-pi-initrd" = {
          Hostname = "10.0.0.22";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
        # orin-nano (Jetson Orin Nano, AI edge node). Same FIDO2-SK-via-agent
        # failure as the Pis ("agent refused operation") — bypass the agent so the
        # key signs. Match the IP too, so `ssh …10.0.0.15` gets it, not just the alias.
        "orin-nano 10.0.0.15" = {
          Hostname = "10.0.0.15";
          User = "martin";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
          ControlMaster = "auto";
          ControlPath = "~/.ssh/cm-%r@%h:%p";
          ControlPersist = "1h";
        };
        # initrd LUKS-unlock stage for orin-nano (manual fallback; Tang auto-unlocks)
        "orin-nano-initrd" = {
          Hostname = "10.0.0.15";
          Port = 2222;
          User = "root";
          IdentityFile = "~/.ssh/id_ed25519_sk";
          IdentityAgent = "none";
        };
      };
    };
  };

  # Desktop Launchers
  xdg.desktopEntries = {
    "launch-nested-dhirujaan" = {
      name = "Nested Session (Dhirujaan)";
      genericName = "Lightweight Wayland Session";
      exec = "sudo /home/martin/Develop/github.com/kleinbem/nix-config/scripts/launch-nested.sh";
      icon = "system-users";
      terminal = true;
      categories = [ "System" ];
    };

    # Override: upstream google-chrome.desktop ships without StartupWMClass.
    # Chrome on Wayland sets app_id = CHROME_WRAPPER = "google-chrome-stable",
    # but the desktop filename is "google-chrome" — GNOME can't match them.
    # This entry's filename ("google-chrome-stable.desktop") matches the
    # Wayland app_id, and StartupWMClass handles the X11/XWayland fallback.
    # Without this, GNOME groups all Chrome windows (including PWAs) under
    # one generic icon instead of matching each PWA to its own desktop file.
    "google-chrome-stable" = {
      name = "Google Chrome";
      genericName = "Web Browser";
      exec = "google-chrome-stable %U";
      icon = "google-chrome";
      terminal = false;
      categories = [
        "Network"
        "WebBrowser"
      ];
      mimeType = [
        "text/html"
        "application/xhtml+xml"
        "x-scheme-handler/http"
        "x-scheme-handler/https"
      ];
      settings = {
        StartupNotify = "true";
        StartupWMClass = "google-chrome-stable";
      };
    };
  };

  # Silencing evaluation warnings from newer Home Manager
  # (Using null adopts the new default behavior)
  gtk.gtk4.theme = null;
}
